#!/usr/bin/env python3
"""bin2c.py <input.bin> <output.h> <array_name> [u32|u16|u8]"""
import sys
inp,out,name=sys.argv[1],sys.argv[2],sys.argv[3]
typ=sys.argv[4] if len(sys.argv)>4 else 'u16'
data=open(inp,'rb').read(); guard=name.upper()+'_H'
W={'u32':(4,'unsigned int','0x%08X'),'u16':(2,'unsigned short','0x%04X'),'u8':(1,'unsigned char','0x%02X')}
sz,ctype,fmt=W[typ]; per={'u32':8,'u16':12,'u8':16}[typ]
while len(data)%sz: data+=b'\x00'
v=[int.from_bytes(data[i:i+sz],'little') for i in range(0,len(data),sz)]
with open(out,'w') as f:
    f.write(f"/* Generated by tools/bin2c.py from {inp.split('/')[-1]} ({len(data)} bytes). */\n")
    f.write(f"#ifndef {guard}\n#define {guard}\n\nstatic const {ctype} {name}[] = {{\n")
    for k in range(0,len(v),per): f.write("  "+",".join(fmt%x for x in v[k:k+per])+",\n")
    f.write(f"}};\n#define {name}_count {len(v)}u\n\n#endif\n")
print(f"{out}: {name}[{len(v)} {typ}]")
