/*
 * m68k_cyc.c — write src/m2_m68k_cyc.h: the 68000's base cycles for each of the 65536
 * opcodes, as Musashi's opcode table has them (m68ki_cycles[M68K_CPU_TYPE_68000]).
 * src/m2_m68k.h charges these per instruction and adds the variable parts itself.
 *
 *   git clone https://github.com/kstenerud/Musashi && make -C Musashi
 *   cc -IMusashi -o m68k_cyc tools/m68k_cyc.c Musashi/m68kcpu.o Musashi/m68kops.o \
 *      Musashi/m68kdasm.o Musashi/softfloat/softfloat.o -lm
 *   ./m68k_cyc > src/m2_m68k_cyc.h
 */
#include <stdio.h>
#include "m68k.h"

extern unsigned char m68ki_cycles[][0x10000];
unsigned int m68k_read_memory_8(unsigned int a) { (void)a; return 0; }
unsigned int m68k_read_memory_16(unsigned int a) { (void)a; return 0; }
unsigned int m68k_read_memory_32(unsigned int a) { (void)a; return 0; }
void m68k_write_memory_8(unsigned int a, unsigned int v) { (void)a; (void)v; }
void m68k_write_memory_16(unsigned int a, unsigned int v) { (void)a; (void)v; }
void m68k_write_memory_32(unsigned int a, unsigned int v) { (void)a; (void)v; }
unsigned int m68k_read_disassembler_16(unsigned int a) { (void)a; return 0; }
unsigned int m68k_read_disassembler_32(unsigned int a) { (void)a; return 0; }

int main(void) {
    int i;
    m68k_init();
    m68k_set_cpu_type(M68K_CPU_TYPE_68000);
    printf("/* m2_m68k_cyc.h - generated by tools/m68k_cyc.c from Musashi (MIT licence,\n"
           " * (c) 1998-2001 Karl Stenerud): 68000 base cycles per opcode. Do not edit. */\n"
           "#ifndef M2_M68K_CYC_H\n#define M2_M68K_CYC_H\n"
           "static const unsigned char m68k_cyc[65536] = {\n");
    for (i = 0; i < 65536; i++)
        printf("%d%s", m68ki_cycles[0][i], i == 65535 ? "\n" : (i & 31) == 31 ? ",\n" : ",");
    printf("};\n#endif\n");
    return 0;
}
