#!/usr/bin/env python3
"""pacrom.py <pacman.zip | romdir> [-o src/pacman_roms.h]

Packs a MAME Pac-Man romset into src/pacman_roms.h for src/pacman.c. That header is
Namco ROM data: it is gitignored, never commit it. Accepts the `pacman` (Midway) or
`puckman` (Namco) set, as a zip or a directory of loose files.
"""
import argparse, os, sys, zipfile

# region -> list of candidate file lists (first set that is complete wins)
SETS = {
    'pacman':  {'rom': ['pacman.6e', 'pacman.6f', 'pacman.6h', 'pacman.6j'],
                'tiles': ['pacman.5e'], 'sprites': ['pacman.5f'],
                'pal': ['82s123.7f'], 'lut': ['82s126.4a']},
    'puckman': {'rom': ['pm1_prg%d.6%s' % (i + 1, c) for i, c in enumerate('ekfmhnjp')],
                'tiles': ['pm1_chg1.5e', 'pm1_chg2.5h'], 'sprites': ['pm1_chg3.5f', 'pm1_chg4.5j'],
                'pal': ['pm1-1.7f'], 'lut': ['pm1-4.4a']},
}
SIZES = {'rom': 0x4000, 'tiles': 0x1000, 'sprites': 0x1000, 'pal': 32, 'lut': 256}
NAMES = {'rom': 'pac_rom', 'tiles': 'pac_tiles', 'sprites': 'pac_sprites',
         'pal': 'pac_prom_pal', 'lut': 'pac_prom_lut'}


def write_header(path, regions, source, note):
    with open(path, 'w') as f:
        f.write('/* Generated by tools/%s from %s. %s */\n' % (os.path.basename(sys.argv[0]), source, note))
        f.write('#ifndef PACMAN_ROMS_H\n#define PACMAN_ROMS_H\n\n')
        for key in ('rom', 'tiles', 'sprites', 'pal', 'lut'):
            data = bytes(regions[key])
            assert len(data) == SIZES[key], (key, len(data))
            f.write('static const u8 %s[0x%x] = {\n' % (NAMES[key], len(data)))
            for i in range(0, len(data), 16):
                f.write('  ' + ','.join('0x%02x' % b for b in data[i:i + 16]) + ',\n')
            f.write('};\n\n')
        f.write('#endif\n')


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument('src')
    ap.add_argument('-o', '--output', default=os.path.join(os.path.dirname(__file__), '..', 'src', 'pacman_roms.h'))
    a = ap.parse_args()
    if os.path.isdir(a.src):
        files = {n.lower(): open(os.path.join(a.src, n), 'rb').read() for n in os.listdir(a.src)}
    else:
        with zipfile.ZipFile(a.src) as z:
            files = {os.path.basename(n).lower(): z.read(n) for n in z.namelist()}
    for name, rs in SETS.items():
        if all(f in files for fl in rs.values() for f in fl):
            regions = {k: b''.join(files[f] for f in fl) for k, fl in rs.items()}
            write_header(a.output, regions, '%s (%s set)' % (os.path.basename(a.src), name),
                         'Namco ROM data - do not commit.')
            print('%s: %s set' % (a.output, name))
            return
    sys.exit('no complete pacman/puckman set in %s (have: %s)' % (a.src, ', '.join(sorted(files))))


if __name__ == '__main__':
    main()
