#!/usr/bin/env python3
"""sharc2h.py <cpresN.exe> <out.h> <array_name>

Turns a linked ADSP-2106x COFF executable (the stf-sharc reassembly of Sonic the
Fighters' SHARC firmware: cpres1.exe = COP, cpres2.exe = GEO) into the header the SDK
uploads to the SHARC (src/cpres1.h `cpres_data`, src/cpres2.h `cpres_data2`).

The image is the one `seg_pmco` section; each 48-bit PM word is stored byte-reversed in
the i960 program ROM, and the SDK array is those ROM bytes as little-endian u16 — the
same array tools/bin2c.py makes from a ROM extract (docs/firmware-extraction.md). Port
of stf-tools cpres.mjs coffSections/pmImage/pmSwap.

    python3 tools/sharc2h.py ../stf-sharc/cpres1.exe src/cpres1.h cpres_data
    python3 tools/sharc2h.py ../stf-sharc/cpres2.exe src/cpres2.h cpres_data2
"""
import os, struct, sys

COFF_MAGIC, SEGMENT, PM_WORD = 0x521c, 'seg_pmco', 6


def pm_image(buf):
    magic, count = struct.unpack_from('<HH', buf, 0)
    if magic != COFF_MAGIC:
        sys.exit('magic 0x%x: not an ADSP-21k COFF file' % magic)
    opt = struct.unpack_from('<H', buf, 16)[0]
    secs = []
    for i in range(count):
        at = 20 + opt + i * 40
        name = buf[at:at + 8].split(b'\0')[0].decode()
        addr, size, offset = struct.unpack_from('<I', buf, at + 8)[0], *struct.unpack_from('<II', buf, at + 16)
        secs.append((name, addr, size, offset))
    found = [s for s in secs if s[0] == SEGMENT]
    if len(found) != 1:
        sys.exit('%d sections named %s, expected 1' % (len(found), SEGMENT))
    name, addr, size, offset = found[0]
    if size % PM_WORD:
        sys.exit('%s is %d bytes, not whole 48-bit words' % (SEGMENT, size))
    img = buf[offset:offset + size]
    rom = b''.join(img[i:i + PM_WORD][::-1] for i in range(0, size, PM_WORD))   # pmSwap
    return addr, rom


def main():
    if len(sys.argv) != 4:
        sys.exit(__doc__)
    exe, out, name = sys.argv[1:]
    addr, rom = pm_image(open(exe, 'rb').read())
    words = struct.unpack('<%dH' % (len(rom) // 2), rom)
    guard = name.upper() + '_H'
    with open(out, 'w') as f:
        f.write('/* Generated by tools/sharc2h.py from %s: %d PM words at 0x%x (%d bytes).\n'
                ' * Sega SHARC firmware (assembled from stf-sharc) - do not commit. */\n'
                % (os.path.basename(exe), len(rom) // PM_WORD, addr, len(rom)))
        f.write('#ifndef %s\n#define %s\n\nstatic const unsigned short %s[] = {\n' % (guard, guard, name))
        for k in range(0, len(words), 12):
            f.write('  ' + ','.join('0x%04X' % w for w in words[k:k + 12]) + ',\n')
        f.write('};\n#define %s_count %du\n\n#endif\n' % (name, len(words)))
    print('%s: %s[%d u16] from %s' % (out, name, len(words), exe))


if __name__ == '__main__':
    main()
